### ISSUE TITLE
Plugin always responds with "ERROR:"

### ISSUE THREAD

**Issue by ansgarradermacher** [bsorrentino/vscode-plantuml-gpt#4]
I've added the PlantUML extension and plantuml-gpt to vs-code. Then I configured my OpenAI API key.
When I open a plantUML file and submit a query in the PlantUML+GPT Window, I always get an "Error:" message (no further information after the colon). It seems that the prompt is never send to OpenAI, at least, it does not appear in my OpenAI activity log.
It might well be that I'm doing something wrong, but the tool should be more robust and provide troubleshooting information.

**Comment by bsorrentino** [comment]
Hi @ansgarradermacher, thanks for feedback 

Currently I use such extension for my work (on MacOS)  and all seems work fine. Unfortunately is not so simple debug an installed VSC extension. I can confirm you that the error is raised when try to contact OpenAI

> It might well be that I'm doing something wrong, but the tool should be more robust and provide troubleshooting information.

You have absolutely right, I'll start to work on asap

**Comment by bsorrentino** [comment]
Hi @ansgarradermacher I've fixed the issue, could you take a chance to test it before I publish ?. 
Please install the attached  [vsix] extension [plantuml-gpt-0.4.3.vsix.zip](https://github.com/user-attachments/files/15567241/plantuml-gpt-0.4.3.vsix.zip) following the instruction below

```
unzip plantuml-gpt-0.4.3.vsix.zip
code --install-extension plantuml-gpt-0.4.3.vsix.zip
```

Thanks in advance

[vsix]: https://code.visualstudio.com/docs/editor/extension-marketplace#_install-from-a-vsix

**Comment by ansgarradermacher** [comment]
Hi @bsorrentino,

thanks for the swift reply and the update. I've checked again and now get a suitable error message, see below. It seems that the plugin does not work with a free OpenAI account. Can you confirm? Is it possible to use GPT 3.5 (for instance) instead of GPT 4.0 to avoid this error (within the limit of a small number of requests)?

--
InsufficientQuotaError: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.
	at Object.o [as onFailedAttempt] (/volatile/home/ar206501/.vscode/extensions/bsorrentino.plantuml-gpt-0.4.3/dist/extension.js:2:577371)
	...

**Comment by bsorrentino** [comment]
> Hi @bsorrentino,
> 
> thanks for the swift reply and the update. I've checked again and now get a suitable error message, see below. It seems that the plugin does not work with a free OpenAI account. Can you confirm? Is it possible to use GPT 3.5 (for instance) instead of GPT 4.0 to avoid this error (within the limit of a small number of requests)?
> 
> -- InsufficientQuotaError: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors. at Object.o [as onFailedAttempt] (/volatile/home/ar206501/.vscode/extensions/bsorrentino.plantuml-gpt-0.4.3/dist/extension.js:2:577371) ...

Currently I use `gpt-3.5-turbo` for simple prompt submission and `gpt-4-vision-preview` for image submission
