### ISSUE TITLE
Failed to process imageUrl: Error: 404 The model `gpt-4-vision-preview` has been deprecated

### ISSUE THREAD

**Issue by Howard-H-WANG** [bsorrentino/vscode-plantuml-gpt#6]
Hey, 
I love this project, but it doesn't seem to work properly in VSCode...

- 
<img width="454" alt="image" src="https://github.com/user-attachments/assets/46dd2813-eba3-4e9e-acff-5f5a8a67204d">

**Comment by bsorrentino** [comment]
> Hey, 
> 
> I love this project, but it doesn't seem to work properly in VSCode...
> 
> 
> 
> - 
> 
> <img width="454" alt="image" src="https://github.com/user-attachments/assets/46dd2813-eba3-4e9e-acff-5f5a8a67204d">
> 
> 

Hi @Howard-H-WANG 
Thanks for feedback.

I'll fix this soon.  Watch the issue #7

**Comment by bsorrentino** [comment]
fixed in version `0.4.4`
